### ISSUE TITLE
OSSMETER Platform - Problem when uploading Jahia Forge - Code Repository

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#28]
Dear All,
when trying to upload to the OSSMETER platform the Jahia Forge - Code Repository project from https://github.com/jahia
I get the following error "Unable to import project. " as in the enclosed image
![troubleimportingjahia](https://cloud.githubusercontent.com/assets/9965053/6186493/6a25f3e0-b37a-11e4-970b-9400d735870a.jpg)

Best Regards and thanks
Alessandra

**Comment by alebagnato** [comment]
same error for https://github.com/joomla

**Comment by davidediruscio** [comment]
Hi Alessandra,

This is because https://github.com/jahia is not a project. It refers to the
page of the user jahia owning a number of repositories. In the import field
of the form you have to specify one of the jahia's repository (e.g.,
https://github.com/Jahia/JahiApp-Newsletter)

Cheers
Davide

2015-02-13 12:18 GMT+01:00 Alessandra Bagnato notifications@github.com:

> Dear All,
> when trying to upload to the OSSMETER platform the Jahia Forge - Code
> Repository project from https://github.com/jahia
> I get the following error "Unable to import project. " as in the enclosed
> image
> [image: troubleimportingjahia]
> https://cloud.githubusercontent.com/assets/9965053/6186493/6a25f3e0-b37a-11e4-970b-9400d735870a.jpg
> 
> Best Regards and thanks
> Alessandra
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ossmeter/ossmeter/issues/28.

## 

---

Davide Di Ruscio, PhD in Computer Science
Department of Information Engineering Computer Science and Mathematics
University of L'Aquila
Via Vetoio, Coppito I-67010 L'Aquila (Italy)
Email: davide.diruscio@univaq.it
WWW:   http://www.di.univaq.it/diruscio
Skype: davidediruscio

## Twitter: DDiRuscio

**Comment by nmatra** [comment]
When you import projects from GitHub, you should use the following URL:

https://github.com/ user/repo name

You are missing the last part.

**Comment by alebagnato** [comment]
Could we add a message saying that as ehancement?
thx!

**Comment by nmatra** [comment]
Do you mean in the error or before adding the project? The latter already exists.

![screen shot 2015-02-13 at 11 25 55](https://cloud.githubusercontent.com/assets/2675111/6186589/3fb9c82c-b373-11e4-9773-2b637d631124.png)

**Comment by alebagnato** [comment]
Hi Nikos,
just instead of " "Unable to import project. "  something like  "Unable to import project because... "

**Comment by alebagnato** [comment]
I posted a potential enhancement at https://github.com/ossmeter/ossmeter/issues/29

**Comment by nmatra** [comment]
OK. Got it.
